### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by gandoulf42** [matronator/lostCountdown#2]
Hi !
Loving this fun project but came into an issue when installing it onto my webserver:

`Access to XMLHttpRequest at 'http://lost.matronator.com/timeleft.php' from origin 'http://10.0.1.1' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
![chrome_2021-05-18_18-36-43](https://user-images.githubusercontent.com/9915997/118690151-0e0e4f00-b808-11eb-8024-a56db3b75ed0.png)

Is there a way to fix this on your side (add 'Access-Control-Allow-Origin: *' in your php response) or eventually provide the source code for **timeleft.php** and **entercode.php** please ?

Thank you by advance.

Best regards,
Gandoulf42

**Comment by matronator** [comment]
Files added 7fd350b381ad5624e4c13308051c0173f265c89c

**Comment by gandoulf42** [comment]
Thank you so much ! :)
